INSERT INTO CARGO (NM_CARGO, NIVEL) VALUES ('Desenvolvedor', 1);
INSERT INTO CARGO (NM_CARGO, NIVEL) VALUES ('Gerente', 2);
INSERT INTO CARGO (NM_CARGO) VALUES ('Diretor');
INSERT INTO CARGO (NM_CARGO, NIVEL) VALUES ('Desenvolvedor', 3);
INSERT INTO CARGO (NM_CARGO, NIVEL) VALUES ('Suporte', 1);