INSERT INTO ORGAO  (NM_ORGAO) VALUES ('Sistemas');
INSERT INTO ORGAO  (NM_ORGAO) VALUES ('Gerência');
INSERT INTO ORGAO  (NM_ORGAO) VALUES ('Diretoria');
INSERT INTO ORGAO  (NM_ORGAO) VALUES ('Suporte Técnico');