CREATE FUNCTION RETORNA_SISTEMAS_USUARIO(CPF_USUARIO VARCHAR(11))
   RETURNS VARCHAR(200)
   READS SQL DATA
   BEGIN ATOMIC
     DECLARE SISTEMA_VAL VARCHAR(200) DEFAULT '';
	 DECLARE CONT INTEGER DEFAULT 0;
		FOR_LOOP: 
		FOR SELECT NM_SISTEMA 
			FROM SISTEMA S 
			INNER JOIN USUARIO_SISTEMA US 
			ON S.CD_SISTEMA = US.CD_SISTEMA 
			WHERE US.CPF = CPF_USUARIO 
			DO
				IF CONT > 0 THEN
					SET SISTEMA_VAL = SISTEMA_VAL || ' / ' || NM_SISTEMA;
				ELSE
					SET SISTEMA_VAL = NM_SISTEMA;
					SET CONT = 1;
				END IF;
	    END FOR FOR_LOOP;
	 RETURN SISTEMA_VAL;
   END