SELECT CONCAT(SUBSTR(U.CPF,1,3), '.', SUBSTR(U.CPF,4,3), '.', SUBSTR(U.CPF,7,3), '-', SUBSTR(U.CPF,10,2)), 
UPPER(U.NM_USUARIO) AS NOME,
UPPER(C.NM_CARGO) AS CARGO,
UPPER(O.NM_ORGAO) AS ORGAO,
UPPER(RETORNA_SISTEMAS_USUARIO(U.CPF)) AS SISTEMAS 
FROM USUARIO U
INNER JOIN CARGO C 
ON U.CD_CARGO = C.CD_CARGO
INNER JOIN ORGAO O
ON U.CD_ORGAO = O.CD_ORGAO