CREATE TABLE USUARIO_SISTEMA (
CPF VARCHAR(11) NOT NULL,
CD_SISTEMA INTEGER NOT NULL,
FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
FOREIGN KEY (CD_SISTEMA) REFERENCES SISTEMA(CD_SISTEMA),
UNIQUE (CPF, CD_SISTEMA)
) 